alias:
    - ccc
    - confuzzius
    - conkas
    - ethainter
    - ethor
    - honeybadger
    - maian
    - madmax
    - mando
    - mando-hgt
    - manticore
    - mythril
    - osiris
    - oyente+
    - pakala
    - securify
    - securify2
    - semgrep
    - sfuzz
    - slither
    - smartcheck
    - solhint
    - teether
    - vandal
    - vulhunter
