alias:
    - ccc
    - confuzzius
    - conkas
    - ethainter
    - ethor
    - honeybadger
    - maian
    - madmax
    - manticore
    - mythril
    - osiris
    - oyente
    - pakala
    - securify
    - semgrep
    - sfuzz
    - slither
    - smartcheck
    - solhint
    - teether
    - vandal
