docker_image:
  default: christoftorres/osiris
cmd: python osiris/osiris.py -s
cmd_bytecode: python osiris/osiris.py -b -s
info: Osiris is an analysis tool to detect integer bugs in Ethereum smart contracts. Osiris is based on Oyente.
